### ISSUE TITLE
 For curiosity

### ISSUE THREAD

**Issue by Baio1977** [bilijp153/ASUS-VivoBook-FL8700JP-icelake-1065G7-Hackintosh#1]
You could attach ioreg of your Hack and\or DSDT origin?
Thank you.

**Comment by bilijp153** [comment]
you can watch new releases ，I uploaded DSDT

**Comment by Baio1977** [comment]
https://drive.google.com/drive/folders/1QbDZh1wbsZm5rg_B7UdgXhBQ0TdeLVvp?usp=sharing
Try this EFI in USB if you start ioreg.
I also need your EFI ioreg

**Comment by bilijp153** [comment]
Sorry, I'm Chinese, but I still don't understand the meaning of EFI ioreg after reading the translation

**Comment by Baio1977** [comment]
https://github.com/khronokernel/IORegistryClone

**Comment by bilijp153** [comment]
ok, i uploaded ioreg
https://drive.google.com/file/d/1cw62vdKw-dYN3KCpQQO838ZW0L-hCWBN/view?usp=sharing

**Comment by Baio1977** [comment]
I made changes:
You have the USBMap kext made with SMBios MacbookPro 16.2 so I put this in configplist, deleted useless kext, try this in USB if it starts a new ioreg.
Ioreg always changes if the EFI changes.
https://drive.google.com/drive/folders/1QbDZh1wbsZm5rg_B7UdgXhBQ0TdeLVvp?usp=sharing

**Comment by bilijp153** [comment]
That, ask this model HDMI can do it? thanks

**Comment by bilijp153** [comment]
That, ask this model HDMI can do it? thanks

**Comment by Baio1977** [comment]
no HDMI on Ice Lake CPU

**Comment by bilijp153** [comment]
ok thanks a lot
