### ISSUE TITLE
Fan control working?

### ISSUE THREAD

**Issue by Bhavinjain260** [bilijp153/ASUS-VivoBook-FL8700JP-icelake-1065G7-Hackintosh#3]
hey I do have a similar laptop vivobook 15 x515ja with ice lake 

fan control working

**Comment by bilijp153** [comment]
My laptop fan is working fine

**Comment by bilijp153** [comment]
> hey I do have a similar laptop vivobook 15 x515ja with ice lake
> 
> fan control working

My laptop fan is working fine

**Comment by bilijp153** [comment]
> hey I do have a similar laptop vivobook 15 x515ja with ice lake
> 
> fan control working

My laptop is normal except for hdmi because it is not officially supported

**Comment by Bhavinjain260** [comment]
Fan control??

**Comment by bilijp153** [comment]
> Fan control??

The fan control is normal. When the temperature rises, the fan will rotate independently. When the temperature is normal, the speed will slow down.
