### ISSUE TITLE
黑苹果安装问题

### ISSUE THREAD

**Issue by 18180419295** [bilijp153/ASUS-VivoBook-FL8700JP-icelake-1065G7-Hackintosh#4]
安装卡在进度条，进度条从无到有动了一丢丢，然后就卡住不动了。

**Comment by bilijp153** [comment]
> 安装卡在进度条，进度条从无到有动了一丢丢，然后就卡住不动了。

你开个- v看看啥问题

**Comment by 18180419295** [comment]
> > 安装卡在进度条，进度条从无到有动了一丢丢，然后就卡住不动了。
> 
> 你开个- v看看啥问题

你好，我是第一次黑苹果，不是很懂，请问在哪里添加-v?

**Comment by bilijp153** [comment]
> > > 安装卡在进度条，进度条从无到有动了一丢丢，然后就卡住不动了。
> > 
> > 
> > 你开个- v看看啥问题
> 
> 你好，我是第一次黑苹果，不是很懂，请问在哪里添加-v?

建议用新上传的版本，然后新手的话建议安装12系统那个稳定

**Comment by 18180419295** [comment]
> > > > 安装卡在进度条，进度条从无到有动了一丢丢，然后就卡住不动了。
> > > 
> > > 
> > > 你开个- v看看啥问题
> > 
> > 
> > 你好，我是第一次黑苹果，不是很懂，请问在哪里添加-v?
> 
> 建议用新上传的版本，然后新手的话建议安装12系统那个稳定

好的，我会使用最新的EFI，系统版本我用的是Monterey12.7.5，应该可以吧？另外我还是不知道哪个-v在哪里添加，原谅我的菜，麻烦教我一下谢谢。

**Comment by bilijp153** [comment]
> > > > > 安装卡在进度条，进度条从无到有动了一丢丢，然后就卡住不动了。
> > > > 
> > > > 
> > > > 你开个- v看看啥问题
> > > 
> > > 
> > > 你好，我是第一次黑苹果，不是很懂，请问在哪里添加-v?
> > 
> > 
> > 建议用新上传的版本，然后新手的话建议安装12系统那个稳定
> 
> 好的，我会使用最新的EFI，系统版本我用的是Monterey12.7.5，应该可以吧？另外我还是不知道哪个-v在哪里添加，原谅我的菜，麻烦教我一下谢谢。

要不你直接点这个首页的QQlogo直接加我qq，去那个上面聊

**Comment by 18180419295** [comment]
> > > > > > 安装卡在进度条，进度条从无到有动了一丢丢，然后就卡住不动了。
> > > > > 
> > > > > 
> > > > > 你开个- v看看啥问题
> > > > 
> > > > 
> > > > 你好，我是第一次黑苹果，不是很懂，请问在哪里添加-v?
> > > 
> > > 
> > > 建议用新上传的版本，然后新手的话建议安装12系统那个稳定
> > 
> > 
> > 好的，我会使用最新的EFI，系统版本我用的是Monterey12.7.5，应该可以吧？另外我还是不知道哪个-v在哪里添加，原谅我的菜，麻烦教我一下谢谢。
> 
> 要不你直接点这个首页的QQlogo直接加我qq，去那个上面聊

你好，我点击QQ跳转有问题，在B站搜索也没搜到，我的QQ是2602235712，麻烦您复制添加一下。
